export const brazilianMusicGenres = [
  "Afrobeat brasileiro",
  "Arrocha",
  "Axé",
  "Baião",
  "Bossa nova",
  "Brega",
  "Brega funk",
  "Brega romântico",
  "Carimbó",
  "Choro",
  "Forró",
  "Forró eletrônico",
  "Forró pé de serra",
  "Frevo",
  "Funk carioca",
  "Funk consciente",
  "Funk melody",
  "Funk ostentação",
  "Gospel",
  "Gospel pentecostal",
  "Hip hop",
  "Indie brasileiro",
  "Jovem guarda",
  "Lambada",
  "Lo-fi brasileiro",
  "Maracatu",
  "MPB",
  "Pagode",
  "Pagodão baiano",
  "Piseiro",
  "Pop brasileiro",
  "Pop rock",
  "Rap",
  "Rap nordestino",
  "Reggae brasileiro",
  "Repente",
  "Rock brasileiro",
  "Samba",
  "Samba-enredo",
  "Samba-reggae",
  "Sertanejo",
  "Sertanejo universitário",
  "Tecnobrega",
  "Trap",
  "Trap funk",
  "Trap gospel",
  "Trap nordestino",
  "Tropicalia",
  "Vaneira",
  "Vaquejada",
  "Outro / fusão",
];
